"""empty message

Revision ID: 250944c9b5e1
Revises: 1aadb1345df6
Create Date: 2022-11-22 11:19:23.991345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '250944c9b5e1'
down_revision = '1aadb1345df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppingcart', schema=None) as batch_op:
        batch_op.drop_column('total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppingcart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', mysql.FLOAT(), nullable=False))

    # ### end Alembic commands ###
