"""empty message

Revision ID: 375444b3b32c
Revises: 250944c9b5e1
Create Date: 2022-11-22 11:24:24.050646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375444b3b32c'
down_revision = '250944c9b5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppingcart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppingcart', schema=None) as batch_op:
        batch_op.drop_column('total')

    # ### end Alembic commands ###
