"""empty message

Revision ID: 81e32c6918cc
Revises: b658225528a2
Create Date: 2022-11-20 13:38:37.468153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e32c6918cc'
down_revision = 'b658225528a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['api_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
